version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

  frontend:
    image: $DOCKER_USERNAME/frontend:latest
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend

  backend:
    image: $DOCKER_USERNAME/backend:latest
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/userAuth
      - JWT_SECRET=SUPER_SECRET_TOKEN
      - JWT_EXPIRES_IN=10m
      - THROTTLE_TTL=60000
      - THROTTLE_LIMIT=10
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
