version: '3.8'

services:
  frontend:
    image: $DOCKER_USERNAME/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api

  backend:
    image: $DOCKER_USERNAME/backend:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/userAuth
      - JWT_SECRET=SUPER_SECRET_TOKEN
      - JWT_EXPIRES_IN=10m
      - THROTTLE_TTL=60000
      - THROTTLE_LIMIT=10
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
